---
applicationName: unifi-ap-exporter
deployment:
  image:
    repository: ghcr.io/robinelfrink/unifi-ap-exporter
    tag: v0.1.9
  ports:
    - containerPort: 9130
      name: metrics
      protocol: TCP
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  volumes:
    config:
      secret:
        secretName: config
  volumeMounts:
    config:
      mountPath: /work
service:
  annotations:
    prometheus.io/port: "9130"
    prometheus.io/scrape: "true"
  ports:
    - port: 9130
      name: metrics
      protocol: TCP
      targetPort: 9130
