apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:NePKDQ==,iv:VIIk/c7uZTyjOrjonGG0/qxWMJYPdoblWTAZnv8RVaM=,tag:SIYzXrRwT9li9Cidpnk70w==,type:str]
  adminemail: ENC[AES256_GCM,data:hVlpqgV8+mGmT2t+gyZme2TifA==,iv:2hSedkL5kOrfDZp6aGOsdRL0CaUZ3ke5XMebDR4sb0s=,tag:tGWNeNDGMEKU1/LNHvht+g==,type:str]
  adminpassword: ENC[AES256_GCM,data:EyVcTFS2pKggtlDZ,iv:A9C/X4N90hAvt3YYrOyTfUo0hPs+8VscEOWPH3RLbws=,tag:yulF9xcfxNN9rPFYBPSUWw==,type:str]
  alermanagersmtphello: ENC[AES256_GCM,data:Pmlj2yGGhzusnje3mjckD2V88QzOq2PrIno=,iv:u7MAXzjhTdj6ThvH0Q9evx2YCKR9Sb44coZ+njDTxRM=,tag:W5NW2Jr2oiuuaV8YRemgtw==,type:str]
  alertmanagerhostname: ENC[AES256_GCM,data:yCZtH0vygY0luFD0C+Q2bHi25BFaxpWrcxY=,iv:Z2J8WOeQdNIzMZQC8E5IdxIpZZkD0gSZJKDE5RqfUmc=,tag:TEVz9Fx6HPHHVQykZ9x/LQ==,type:str]
  alertmanagerurl: ENC[AES256_GCM,data:+vhfL4kWU9QevWrVIvyK6D7XA66POqt5fjBMglgvOxTcCw==,iv:03ZH+twfJTd1hwGJYPZb2+6CGe2gztDPEvf68RaXyD4=,tag:FKFWQ15ytfXmxLT3qIl/5A==,type:str]
  alertmanagersmtpfrom: ENC[AES256_GCM,data:SFM3jROPJXAn11Bt7u2sHcWrolOj3oD+tRw=,iv:XkZMYZeTxHom2hQSJPiKdYxgIefat7+1yzv9PRwJqzM=,tag:+on0TSQoFwmuXy8B4xRvlQ==,type:str]
  alertmanagersmtpsmarthost: ENC[AES256_GCM,data:bWI0INqUGH1JiJH728i74Jt7H/8=,iv:bjfVbaoJwn//V0NONqpN71M+N9JvkqpseaV+IM9hq5E=,tag:VIq0DMw4TzSb5x6qPF1S3w==,type:str]
  alertmanagersmtppassword: ENC[AES256_GCM,data:T0ALMQHXAi8=,iv:OD4ipPuund3q4ws13pWLrt6pXcnbczQ/kPyNBaMxx7Q=,tag:R1q1J5BOwZ5VxiIDZJZShQ==,type:str]
  alertmanagersmtpusername: ENC[AES256_GCM,data:f9duB4s=,iv:2rc4ddyusylM/+k4j+qC+ivnCUBgIQDaksEj4QOIPcY=,tag:0Fvd/PA+T89rAImfb2ZKAg==,type:str]
  grafanahostname: ENC[AES256_GCM,data:CcfiyB0XOkwJndlOxoW5OyGEfQbW,iv:OYNijxSTL30Q8IObuJkHwyjxEPkTGmtMQ5l+9VUSQOw=,tag:UnSG6/B6Kz5AgNNZ86q0QA==,type:str]
  prometheushostname: ENC[AES256_GCM,data:fb6cKAku7GtkN0gO9aoH7b+0v6SIrfTU,iv:lEyPbSju6MBnt+oi3fbOSgzFQfe2dGM1B09odjxNi7E=,tag:yCiqakeQ5jNP1gDPYVsV3Q==,type:str]
  prometheusurl: ENC[AES256_GCM,data:d0/hxb4Pqp+GDPP+YQ+EZHo5gyPk+oYnk2O12495SZA=,iv:M/QHqc/5E8KaMgyCmE+H11ql2n+g+LxQDcHaOlYw5yY=,tag:eLlEFsoFMZL1bebOfup2ig==,type:str]
  grafanaclientid: ENC[AES256_GCM,data:eyrIxvUgolkRG6PpEDXn2TjrXTczPsQp8spCgD4gX3qc7f2dELlR9A==,iv:y3YG52jyK0K4zUPpTVVVNNTFUFyXif6wVmK2lzfonEA=,tag:G75l7YC8hiuAcPXvnUed5Q==,type:str]
  grafanaclientsecret: ENC[AES256_GCM,data:/kIDyiNYfmWPG22jY4ZUkblHcDtwnu68W15DE6S0yktaTeZi+WWhfq4a8Bw2LVxC+9fejcl/j7Pj1yipV8PTNkOeC91IMHEfuHWysX7MP3jWYsZTusIaLKH7CDPCsAsqQjtWqU7LiwSaCv+DMrWrA7YCiTYVgxb9gcK9Zk9JZKA=,iv:Tp9SVF/z+efVI3F6J0WxQMVaqM+r8T/PF6j62d9rfk4=,tag:fxzsIN5Kb9bvXPEfQDvWAw==,type:str]
  authentikhostname: ENC[AES256_GCM,data:v8EHkVIi99A3EKHIKzEBVhC/,iv:pP/U8LlZyi+qGLZKA/S/f37CU2aprytkWvLPOi6uUaY=,tag:Y2lu+Yq8pC045UomUEexyw==,type:str]
  grafanarooturl: ENC[AES256_GCM,data:2IrQcok5qN8FIYZV9mT55nGzosPAtuyz1f3WHD8=,iv:GGbaJtxt0Ps3nugKdBzN8VCxAr4y2HGbDknh/oAlSL4=,tag:JczJS9aUquiHNmaCr7+cnA==,type:str]
  grafanaauthurl: ENC[AES256_GCM,data:dcr2pSlT26oadQw5D3UDaNWrZaOiM5CuTO8clpnsh4g3Nng21aT8qc2G8P3+XPUZv51c,iv:6DiAkeQAo5ZDU4n1VXOGrZMrEA5YWq9HK8l6NOqPCMs=,tag:0UmZpyJNEtMFdbyhUCiw0Q==,type:str]
  grafanasignoutredirecturl: ENC[AES256_GCM,data:Buxqsq47kUoqITrj7Oapt0ETAFeF5VyJzqYHsoknGa/W8R52tsKX9WSSO8L2ziY2fOSMa+rmTRuWCDhHyw==,iv:vn2sd1R09e1GGPSjolbWbkhK64802rreCy1C0hGJ50s=,tag:63i39fOhqjJ4vOXkvf8zQg==,type:str]
  grafanatokenurl: ENC[AES256_GCM,data:rgAFv1e4UjduRO/3uRPCFPrgA5eVel3m3B8mFRvbsTfOjBGp+F0URSCGzITjsfI=,iv:ZhUurVRorTSNXo8/pbBJn328c16KUBTBBx2Q2ani58w=,tag:mvdax3N2AGp2KW9bMKBQrg==,type:str]
  grafanaapiurl: ENC[AES256_GCM,data:KA9GEIRsWQ5XYoIDoBDte606rQgGkY4ZdvNlCEfNcGpjQazWncRR9hRO4VTlUH+2qWI=,iv:4PtuOm5e9Lq0xoABsbbWsO/TvZnm93TK508l1QkOV/Y=,tag:JkuLdo2DmM0ajhwjNbcElw==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NmZobmNpNmkrK3AzTHRZ
        aUNhWUlsK0ZzRVhHbm9aaGZ0TjVOZU5qeFYwCk90a09ub0FGakkxNjM2WGlkOWVj
        RVhKdTQ1NEpCK3BNQnlGZEFxTzZLZ0EKLS0tIFNLL21IdzRYUE91WXg5dmx3Mys4
        RWg2UzJkNXRDSlQ0V3h1VVlNRktzUWsKzBPtIipBb3UWLFhGDzNyOYH7qs/MKqAu
        c+umSnX3Rx0vneYsowqSVj3c5mdf6h1RfWxYtGNjBY6xCLjAaJPGDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T10:12:49Z"
  mac: ENC[AES256_GCM,data:cQKStQfI0dVVS1u3sD24ltDDR/vgTquPB1mCf3N/9rlo/zkqtHFIiWWSDDcAEzqC7akkLr4grWWZBURuYaYgxN7dKRUOVjZX2L2QkxVh/MJzd0REA5MAb1GraotzOH1V3Jl0YZB/Y+u2+HH0v5bjC2XZCNPF4vma156SAhuOImU=,iv:832RjickoaGJ1Bf07evuLn24fW64/xfIOuuNza5Q1yQ=,tag:7jsYRRw1J513X1LTCsFvDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
