apiVersion: v1
kind: Secret
metadata:
  name: gitea
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:Jwe5Nw==,iv:fpbRnkZLf1ru5RrTtUigok5shAq7TmmATqjM66NEnoc=,tag:3dVgq/flVjK6gbAlCI4JOw==,type:str]
  hostname: ENC[AES256_GCM,data:2UiI6BvhVdjsNM+sjgtCo0c=,iv:WdDPqf5THiiFU5piuXVwid5DoQ67T38RUPbAz7qPIEc=,tag:pQ5rtvvt5MGl5O6AimQmrg==,type:str]
  adminpassword: ENC[AES256_GCM,data:2aLGBWURSJ55YLBe7P4=,iv:RkTGmzAOR5fNTcgtn3LkjDk1B/d/6MGKZnmjmfKGIh8=,tag:/scLb+LKXx99u5d++zp8fg==,type:str]
  oauthkey: ENC[AES256_GCM,data:8RM2p+gVvVhoVVeh58gf35y/2hunQxmnOqtOvDokBptB+HVAOR56Ew==,iv:WAtkkwX5p/+BMlOtG1kUkmFlfA8U27uRbmI/0//ik2k=,tag:gslQJRq0jiwT+OSRulLqxA==,type:str]
  oauthsecret: ENC[AES256_GCM,data:8w2lcEvtmf4xCaIRAmlhzo/I5T2+x1m+B18t00Pbm3c53vzlcG5TPPWR3akt4V4w3DCrsaGmSDcplyJ3mFWaLKggCES3JOLtbrpoAVjY6Gl7la3motiYo+x7PNul7aF+WCPaC7tdr6nJUJxgsLjTIjy0OIoUxjA1KUdcxv2WqdM=,iv:iWodx1PgFbwzRD5LUZ9RRNcHIOAoXFPKROxDKbKjNu8=,tag:2L/ZMJcYVC2QiYFpGJSvjw==,type:str]
  oauthdiscover: ENC[AES256_GCM,data:HPK6S1xrkFZ6aXPSpjO5qC4G4pO95r5+EZ7CBQgmQru0SOKcFNaXC/JzqJbohFKPnFLatou1QHwbUQb8sHb+RRE4KkHVJDsOX0e3mwdUHg==,iv:K4DXONDwPv97Mwl5V0tZwiTyOJV3efgnpEGcQusJekI=,tag:Slo2zHYq3TLHKstx+eOTrA==,type:str]
  smtphost: ENC[AES256_GCM,data:qBUgZkkLLdrOFpC19BD1tdfV,iv:4Xw1iyZgT27sObJtyqyRXBrl3Db6HhEq8LGRv3JSdeQ=,tag:gZmc3srkTSk50JgomKzjOw==,type:str]
  smtpuser: ENC[AES256_GCM,data:OlpOpgNkXXdYw1w89OG2cdxFiQ==,iv:Cb5dUOxc7UiJdhFCgeZmHIFfeJxKfgZjVm2LCSZQXBE=,tag:eZ7LBHJgiY7bcvsHXylzGg==,type:str]
  smtppassword: ENC[AES256_GCM,data:CCJzbIBu+7r2orKEUE8=,iv:gIrHegHB0BoFzOFPMsi9B0rv8NhhQl5J5GRv7qVf2rs=,tag:tr6Mb7jhnsLA2G7hRSL4dg==,type:str]
  smtpfrom: ENC[AES256_GCM,data:i44St9JOaFWVpFyXhcbvvEnX3Dx2ubSaIP/g,iv:dDIxuu9nRzmDtMqi4dFRNw2J2PEFITxIIwI32r8TtBU=,tag:OgoeYzd+mqp3Nib/fa+fRA==,type:str]
  smtpenvelope: ENC[AES256_GCM,data:6KVnnBRhHQG6/AAJK/4cbOaLMbOs,iv:1gnXWxpVqXfnCWY7cVwOh/7vuD3A4RuFhCMspsj1VgI=,tag:kh4txnNIi8uqmVO3tGVTbg==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdk5yWEpObFdkSERrUjZm
        VFNsMElaZUZjc3F4bjA0UzFXcnJnMWhVaGdVClA4c3NlVllDUmdZMnNMcjdHYUo1
        K0xsUjF1eHdrUVJEVkg0RHNZVU9yQzgKLS0tIDZ3M0FmYkVMdmExazBNY1V1NXZi
        OXNxMVJQWStKbDdLSkwxc2xxS2NYOUkKqDvCSYQ+RvdiVz5vCEUHp7fkCWajh59d
        qf/17mythv2MW/CF/u5bQ5y6tZh8toOkYr7yatIdAS741EHPouvSKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T10:43:18Z"
  mac: ENC[AES256_GCM,data:EDkBzp5NzbWcXOfL4wMR7pOouqY4CvBN6rVXkO6t1b4HTvWJhK9pvsBcLrMUiQAbnLQFFVAVQL3qJLp5XDddjXg5DGHQSkMpmM5tI4qZIbwPQGGs6h+pEAjtCaUqgZVG0dau7vbMuG7608nWUezom01loKxJVqaCmmO68PuU054=,iv:aEqla8KpZbNwsx12aI+8D8g7V8f1rJ4Jf3aWxrY4Vvk=,tag:0BvrfrahyemZ7gtTRqD1cA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
