---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: haproxy-ingress
  namespace: haproxy-ingress
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: haproxy-ingress
  ingress:
  # In-namespace
  - fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": haproxy-ingress
  # HTTP
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      - port: "443"
        protocol: TCP
  # Prometheus
  - fromEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": prometheus
        app.kubernetes.io/name: prometheus
    toPorts:
    - ports:
      - port: "9101"
        protocol: TCP
      - port: "10254"
        protocol: TCP
  egress:
  # In-namespace
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": haproxy-ingress
        app.kubernetes.io/name: haproxy-ingress
  # Kubernetes API
  - toEntities:
    - kube-apiserver
  # DNS
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
  # Other namespaces
  - toEntities:
    - cluster
