apiVersion: v1
kind: Secret
metadata:
  name: nextcloud2
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:wVqf5g==,iv:eOF8vIkkH3IGJh0Zu25pNssvkE3GsPHvNS62Mx5YuEY=,tag:0hLv0UY3hoBSE9f/PBHPHg==,type:str]
  hostname: ENC[AES256_GCM,data:DD8BXmKKTEJXERAr/ajre06sY8Gl,iv:gQ+c+eFa/lT7z2MCmosq7LgPsXB7qtgaGeq5ktEp11M=,tag:alrbHmba3Vm9oJ26fxRWUg==,type:str]
  collabora_hostname: ENC[AES256_GCM,data:EvvXEhalvyHiXg4641Y1wtLIemBz++lWYlThZw==,iv:HpbKzBgIn9dFhI3aJb7Tl5d0gphnr9IwtwK4wpak/4k=,tag:dzoPPUITN+q/VQ6I/Wd+nA==,type:str]
  mailfrom: ENC[AES256_GCM,data:L+vRTQ==,iv:LXdCmSEfYkcRxKwCA6Z0oVGxnsL0T9umhZ2jCtLlQrE=,tag:S9prRvSAPGlxW57PbqatgQ==,type:str]
  maildomain: ENC[AES256_GCM,data:V81JSbwzCidKB1L7AYCj7Q==,iv:97+woFnG1MlCrJXdM+ZaCi1BzikIiIpec2tmWU6XpJc=,tag:QS1YZfHTt0qfpjYaM3hpwg==,type:str]
  smtphost: ENC[AES256_GCM,data:IVsni4YXuXygXEh45LlVErXg,iv:8PvMEUZ4NBQwK3mSxwHaDI7QD9nWMSbVXHl3GbUPOJ0=,tag:6CIBcycu3GverEYZS5SQAw==,type:str]
  smtpusername: ENC[AES256_GCM,data:z+as3z5hIfm+n2jEEBggNrm8xvFTb0RN652+JEwkrQ==,iv:cRwmFSq3ffiUxJc8t24uz0fg+q+5H9OshuIY+sFN4rk=,tag:zrRkVHQ7Vy9ZBQCE6bKp8A==,type:str]
  smtppassword: ENC[AES256_GCM,data:vUgo4Dy3Go+XnUf39FM=,iv:noGWcFqoiubm9pxlRcKv9YH+AdyeQyDJznDIsV34B0w=,tag:On4ZQIWZERCS+TAE2v12wA==,type:str]
  backupusername: ENC[AES256_GCM,data:vdj/2HrtbTM=,iv:xkOe693f4zoxTW8FbiVXzDXBupAHmbVBWo5/Y4kFYHw=,tag:WvGSl22KiZ9XfHV6ERdNOg==,type:str]
  backuppassword: ENC[AES256_GCM,data:Td8cnLwu/vbnAPrt,iv:jjOZkt6rrGwCJ7CofwH3ZYkoK6X2ezAPH9oXcgXhk2c=,tag:Xv2PSRX+c/AiEQeh342u1g==,type:str]
  backuppasswordencoded: ENC[AES256_GCM,data:6JFYmTOQuhvT6o3ezl4=,iv:6IgbBEi+VxImnW4RK22+GzNa2HNyFoiRxo31+9tlmto=,tag:Zhs8KU+81dZJUyQFeiF8dw==,type:str]
  backuphost: ENC[AES256_GCM,data:VnxM4DEDGGFVMpAxkBen9i9e8vYkdbPAHiz25sz2,iv:uuU2ZPywaMwn4FVLVPeFDc77j1sHxnYwcoxbiltx0sc=,tag:A23sc9SH4TeUFaocpsXkDg==,type:str]
  backupurl: ENC[AES256_GCM,data:YEVfX+srOF1lMjY678gjEW6tPeJjBOYSkbb3Ws4dg5UV2SzfW89LOD3Qdym7sXXmYwKb,iv:HbXdcZKf0AgO94xbvNj3tjpJBgV2OrqYUGTymD4KIys=,tag:yfnMohzRv7qen2ypqoZfdg==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSTFZTk5ySHVMUEdnM3Qv
        Tmlob3dWanpReVlVekdIWU8vVFVTS1ZQSlVBCmtiVXJrYWtQSVlodnhFeTBsWjAw
        eGt0MnE0SWJXR0VBeDRtazVjNVg3V0EKLS0tIHFYSUM2c0dkOHp1WGVKeGFlczlQ
        MVVDaFZMenB2aXhJVnJJbmthTEVKVU0KTks1PXgTcXqxn9JZHBh5fhx8x4YXKgWZ
        /tqqF/wbD0DM87SWIleOK0jYf+hmA6dm83aEkMclseY+ob3X+HzD2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T11:33:34Z"
  mac: ENC[AES256_GCM,data:alROwnHvWJo/595JhxUeVQZ9YMwLbtjO0vOFaW16/6vfyAqAjIPyCSsF6K1O/m+1E9EePMvemqrH4duq/lwPhY2KuZGA+9091f2qaATeS06gka8geHJdu/1GnD5YbPJe+2bBttJyjy9pKoamKk56OK5PQ0iTjfw9mMq7lcXLHTc=,iv:HRpKOl8notxDkUFFtMQCeRHqzVgei/mSoVIYKBgBsDw=,tag:SHHV/m7ySRp2GCbGZEJtyA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
