---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud2-valkey
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: valkey
      version: 0.9.2
      sourceRef:
        kind: HelmRepository
        name: nextcloud2-valkey
      interval: 1h
  releaseName: valkey
  targetNamespace: nextcloud2
  storageNamespace: nextcloud2
  dependsOn:
    - name: prometheus
