---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy
  namespace: flux
spec:
  interval: 1h
  chart:
    spec:
      chart: haproxy
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: haproxy
      interval: 1h
  releaseName: haproxy
  targetNamespace: haproxy-ingress
  storageNamespace: haproxy-ingress
  valuesFrom:
    - kind: ConfigMap
      name: haproxy
      valuesKey: haproxy-values.yaml
