---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: haproxy-ingress
  namespace: flux
spec:
  interval: 10m
  path: ./manifests/haproxy-ingress/resources
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: kube
  dependsOn:
    - name: cluster
