---
controller:
  ingressClassResource:
    enabled: true
    controllerClass: haproxy
  kind: DaemonSet
  config:
    use-proxy-protocol: "true"
  service:
    type: NodePort
    httpPorts:
      - port: 80
        targetPort: http
        nodePort: 31080
    httpsPorts:
      - port: 443
        targetPort: https
        nodePort: 31443
  haproxy:
    enabled: true
  metrics:
    enabled: true
