apiVersion: v1
kind: Secret
metadata:
  name: vcluster
  namespace: flux
type: Opaque
stringData:
  nodename: ENC[AES256_GCM,data:VAximg==,iv:0BCtxUMk9Sprco0rnKL7036umr+9J3sdB7uUaMrHTn4=,tag:wjxLyw2vvYx+0yzXp0xG5Q==,type:str]
sops:
  age:
    - recipient: age17ek4wa64lwdkn8xu6suz94jp73qpxj2mr9gaa40wecayy8lsrg3qcxhwv4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV2NyRkJXVkpyejhtZnRX
        SnZXVmQ1TVF2K3BEU0R0NW1rWmlMSFhTOXpVCi9JTVpLQStvaDJsQUhoMkhvak1v
        NDV4YmlsTTAxNmdsRzZjeEgyYVVrdlEKLS0tIFJlMkRTRVhEWSttUFZUSW1SQ0c5
        SEJUSkMwcE9IQWxQdUdEK0d3UFA5K1kKpgkETDavPjQHRi42lH+mLJRCtIoBIiF9
        1JxRQTHCWEeyZOGzUTqvvimw1NctsW1E3W4jOm1pCM9MvMgWdfIdAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T10:37:38Z"
  mac: ENC[AES256_GCM,data:N+/qPT+UbvE29a027ZvHPE2VqoR+xYIRdQEm+b3tUi3xsa4/nILI+ZbpEg3lrKAYOaDQ4dKwUuwxKQr94MdQjZIhvTAqXuAM927wh4nkWi7f0mk27hbtA4iXL9/gxpQg7Y+PA6Y1XbtkNF59pB3OsLl4taPrBdeWYeMx4TdgMx0=,iv:aIHzXOo6IvL40kfsRmg/TOL5L+zwjcfEGianHqrNcYQ=,tag:1b5bRjpr9Bkq4vq6hTiY8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
